# ----
# Site

title: Oliver Gibbs
url: "https://gibbsie.github.io"
baseurl: "https://gibbsie.github.io"
google_analytics_key:
google_maps_javascript_api_key:
disqus_shortname: gibbsie-github-io

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Random technical musings of Oliver Gibbs
author:
  name: Oliver Gibbs
  email:
  twitter: gibbsieorg
# social:
#  name:
#  links:
#    - https://github.com/

# -----
# Build

timezone: Etc/UTC

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  staff_members:
    _hide_content: true

paginate: 10
paginate_path: "/blog/:num/"

jekyll-archives:
  enabled: ["categories"]

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      type: "posts"
    values:
      layout: "post"
      _options:
        image:
          width: 2000
          height: 1322
          resize_style: cover
        content:
          width: 1500
          height: 2000
  - scope:
      path: "contact-success.html"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "pages"
    values:
      image:
        width: 2000
        height: 1322
        resize_style: cover
      bottom_image:
        width: 2000
        height: 1322
        resize_style: cover

# -----------

social_icons:
  - Facebook
  - LinkedIn
  - Twitter
  - YouTube
  - Email
  - RSS

_comments:
  description: Technical musing of Oliver Gibbs
  blurb: Cloud SME specialising in cloud, DevSecOps, infrastructure, security & web apps.
